Ignore from_iter_instead_of_collect clippy style lint
    error: usage of `FromIterator::from_iter`
       --> src/lib.rs:266:16
        |
    266 |               Ok(TokenStream::from_iter(
        |  ________________^
    267 | |                 vec![
    268 | |                     TokenTree::Punct(Punct::new('#', Spacing::Alone)),
    269 | |                     TokenTree::Group(Group::new(
    ...   |
    292 | |                 .chain(input),
    293 | |             ))
        | |_____________^
        |
        = note: `-D clippy::from-iter-instead-of-collect` implied by `-D clippy::all`
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#from_iter_instead_of_collect
    help: use `.collect()` instead of `::from_iter()`
        |
    266 |             Ok(vec![
    267 |                     TokenTree::Punct(Punct::new('#', Spacing::Alone)),
    268 |                     TokenTree::Group(Group::new(
    269 |                         Delimiter::Bracket,
    270 |                         TokenStream::from_iter(vec![
    271 |                             TokenTree::Ident(Ident::new("cfg_attr", Span::call_site())),
      ...

    error: usage of `FromIterator::from_iter`
       --> src/lib.rs:275:33
        |
    275 | / ...                   TokenStream::from_iter(
    276 | | ...                       vec![
    277 | | ...                           TokenTree::Ident(Ident::new("all", Span::call_site())),
    278 | | ...                           TokenTree::Group(Group::new(
    ...   |
    285 | | ...                       .chain(then),
    286 | | ...                   ),
        | |_______________________^
        |
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#from_iter_instead_of_collect
    help: use `.collect()` instead of `::from_iter()`
        |
    275 |                                 vec![
    276 |                                         TokenTree::Ident(Ident::new("all", Span::call_site())),
    277 |                                         TokenTree::Group(Group::new(
    278 |                                             Delimiter::Parenthesis,
    279 |                                             TokenStream::new(),
    280 |                                         )),
      ...